path_to_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data

wandb_entity: VDKI-Hasen
wandb_project_name: VDKI-Hasen
wandb_experiment_name: experiment_cifar_cats_and_dogs_transfer_learning
learning_rate: 0.001
seed: 42
batch_size: 256
max_epochs: 50