path_to_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data

wandb_entity: VDKI-Hasen
wandb_project_name: VDKI-Hasen
path_to_data: "C:\\Users\\lobster\\Documents\\HKA\\Kurse\\VDKIß\\Projekt\\data"
wandb_experiment_name: experiment_cifar_cats_and_dogs_transfer_learning
learning_rate: 0.001
seed: 42
batch_size: 128
max_epochs: 50