path_to_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data
path_to_test_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/Test_Dataset
path_to_train_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/Train_Dataset
path_to_val_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/Val_Dataset

path_to_raw_pics: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/data_scraper/Google-Image-Scraper/Bilder_Marie
path_to_split_aug_pics: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/Datasets_aug

# path_to_bunnie_data: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/dataset_aufgabe2_cropped_raw
path_to_bunnie_data: D:\HKA_IMS_Drive\SS25_MSYS_KAER-AI-PoseAct\21_Test_Data\dataset_aufgabe2_cropped_wo_duplicates
path_to_bunnie_data_aug: D:\HKA_IMS_Drive\SS25_MSYS_KAER-AI-PoseAct\21_Test_Data\dataset_aufgabe2_aug

path_to_models: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/Models/CNN/
path_to_model: D:/HKA_IMS_Drive/SS25_MSYS_KAER-AI-PoseAct/21_Test_Data/Models/CNN/TL_ConvNextV2_base_model_20250628_164550.ckpt

wandb_entity: VDKI-Hasen
wandb_project_name: VDKI-Hasen
wandb_experiment_name: Face_Recognition_EfficientNetB4
trainable_linear_layers: 1
learning_rate: 0.001
seed: 42
batch_size: 32
max_epochs: 50
image_size: 128
#name_list: [unknown, kaninchen, maus, ratte, eichhoernchen, frettchen, katze, hase, hund, igel, mader, waschbaer, siebenschlaefer, meerschweinchen, schlange]
name_list: [other, apollo,  aster, helios, nyx, selene]
#image_scaling_factor: 1