path_to_split_aug_pics: /Users/mariewinkler/Documents/HKA/S2/VdKI/Bilder/Datasets_aug

wandb_entity: VDKI-Hasen
wandb_project_name: VDKI-Hasen
wandb_experiment_name: experiment_cifar_cats_and_dogs_cnn_learning
learning_rate: 0.001
seed: 42
batch_size: 32
max_epochs: 10
image_size: 128
#name_list: [apollo,  aster, helios, nyx, selene]

# zum testen
name_list: [kaninchen, maus, ratte, eichhoernchen, frettchen, katze, hase, hund, igel, mader, waschbaer, siebenschlaefer, meerschweinchen, schlange]

#image_scaling_factor: 1